name: Build Docker Image

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:.devcontainer"
        push: false
        tags: sigrok-dev:latest

    - name: Run test script
      run: |
        cd .devcontainer
        ./test.sh
